[package]
name = "autodata-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest =  { version = "0.12", features = ["json"] }
serde_json = "1.0.122"
tokio = { version = "1.39.2", features = ["full"] }